keys:
  # Users
  - &users:
    - &thomas EE0DAA80933D8C289C09A2470FF792378ECC5F3A
  # Hosts
  - &hosts:
    - &wilfred age10yrhns4kn9h83n7v29uqzq60nl0tyfh5ld62afxvk5tkhuk53fmsxdgkh5
    - &agnes age10yrhns4kn9h83n7v29uqzq60nl0tyfh5ld62afxvk5tkhuk53fmsxdgkh5

creation_rules:
  - path_regex: hosts/wilfred/secrets.ya?ml$
    key_groups:
    - age:
      - *wilfred
      pgp:
      - *thomas
  - path_regex: hosts/agnes/secrets.ya?ml$
    key_groups:
    - age:
      - *agnes
      pgp:
      - *thomas

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *wilfred
      - *agnes
      pgp:
      - *thomas
